### ISSUE TITLE
aria-roledescription in JAWS

### ISSUE THREAD

**Issue by maschad96** [wnolfm/a11y-slider#12]
There have been a few reports of issues where the aria-roledescription text is read after reading each semantic node nested within it. For now, leave out of working copy until further update from JAWs and a confirmed resolution

Current suggestion is to replace with an aria-label:
https://github.com/FreedomScientific/VFO-standards-support/issues/154#issuecomment-512786380

Issue reference:
https://github.com/FreedomScientific/VFO-standards-support/issues/154#issuecomment-516035301

**Comment by wnolfm** [comment]
@matthewschad Carousel Items currently have a `aria-roledescription` and `aria-label`. 
```
<div class="carousel-item"
                    role="group"
                    aria-roledescription="slide"
                    aria-label="6 of 6">
```

Should we just remove  `aria-roledescription` in this case?

**Comment by maschad96** [comment]
Yes, would just combine as 'Slide 6 of 6'.

Same goes for the `<section>` node, would revise to

`<section id="myCarousel"
         class="carousel"
         aria-label="Highlighted television shows, carousel">`, rather than having `aria-roledescription="carousel"`
